[ _ ]
    schema-version = "0.2"

[io.buildpacks]
    builder = "paketobuildpacks/ubuntu-noble-builder"

[[ io.buildpacks.group ]]
    id = "paketo-buildpacks/cpython"
    version = "1.18.7"

[[ io.buildpacks.group ]]
    id = "paketo-buildpacks/procfile"
    version = "5.12.0"

[[ io.buildpacks.group ]]
    id = "paketo-buildpacks/pip-install"
    version = "0.7.11"

[[ io.buildpacks.build.env ]]
    name = "BP_CPYTHON_VERSION"
    value = "3.14.*"
