[ _ ]
    schema-version = "0.2"

[io.buildpacks]
    builder = "paketobuildpacks/builder-jammy-base:0.4.516"

[[ io.buildpacks.group ]]
    id = "paketo-buildpacks/python"
    version = "2.40.3"

[[ io.buildpacks.build.env ]]
    name = "BP_CPYTHON_VERSION"
    value = "3.13.*"
